### ISSUE TITLE
venv and .idea directories

### ISSUE THREAD

**Issue by gadhagod** [shaunikm/CalculatorGUI#1]
Isn't the only file needed for this main.py? Why have venv and .idea directories? They have over 1000 files, will take up space on a computer, and are unnecessary.

**Comment by shaunikm** [comment]
That is just for the repo. In the releases, you can download main.py exclusively.

**Comment by gadhagod** [comment]
Most developers use their command-line. I would rather be able to clone the repo with only the useful files from the terminal. Just a suggestion, because the others serve no purpose, right? Or am I missing something.

**Comment by shaunikm** [comment]
That is a valid point. I will try to change that as soon as I can.

**Comment by gadhagod** [comment]
Still no update?

**Comment by gadhagod** [comment]
Still no update?

**Comment by gadhagod** [comment]
Still no update?
